### ISSUE TITLE
Found two Vinyls that are not on the map 

### ISSUE THREAD

**Issue by NightHunter27** [joric/maps#2]
One is in the pindar as part of the quest The Lost Tommies (located next to the Blackwall Citadel and Polaris Apartments and east of East Wintergarden. This one is missable as well following one of the steps of the quest towards the end of it. (Vinyl titled Ol' Nuclear Winter)

Another one is located inside the Eastminster Slums. There is another door within that takes you into another cell and it is one of the rooms there. Accidentally stumbled upon it as part of the NuSkin new you quest from Westminster.  (don't remember the name of the vinyl and I have quite a few now in my collection) 

Sorry for posting as an issue, I did not know how to flag this up :)

**Comment by joric** [comment]
"Ol' Nuclear Winter" added by remapping the cell and can be searched. Second one not sure.

**Comment by NightHunter27** [comment]
I will do a cross reference with what I have tagged as collected on the map and what I have in my collection and find the name of the other vinyl.

**Comment by NightHunter27** [comment]
In the meantime, I have found that  "That Girl from Valley Road" vinyl is not in the south of the map on or close to that big farming machine. And on this following link, it says it is in Westminster in the corner. I am yet to verify this:

https://fallout.wiki/wiki/Mod:Fallout_London/That_Girl_from_Valley_Road

**Comment by NightHunter27** [comment]
Found the "other" one. It is Train Line Romance in the National Portrait Gallery. I was able to find it now. Maybe I have done a mistake initially. My bad :)

Ol' Nuclear Winter still shows up in Tower of London on the map instead of the pindar, idk if there is a way to reload the map other than refreshing the page

**Comment by joric** [comment]
@NightHunter27 i've added proper doors, the map now has more markers (3781 -> 6333), check it out.
