### ISSUE TITLE
I found a CuteThulhu doll that is not on the map. 

### ISSUE THREAD

**Issue by jorisrietveld** [joric/maps#4]
Hey I found a Cute Thulhu doll that is currently unmarked on the map. Its on the train during the "Black" quest at Canning Town. 
![Screenshot_2024-11-14_01-10-02](https://github.com/user-attachments/assets/6f87927e-fb6e-4c52-aa17-6c2f077c8b89)
![Screenshot_2024-11-14_01-09-24](https://github.com/user-attachments/assets/0084a408-0034-4576-9aec-7ef47295c92f)

**Comment by joric** [comment]
Maybe your game is not 1.02? 1.02 locations were updated. This room looks similar but not quite.
![image](https://github.com/user-attachments/assets/f9bd81cb-bbde-4d9d-a72c-1e3f2dc1a3a4)
How I got there:
startquest 072B6593
setstage 072B6593 30
got to train went through the train
Next time get the reference id for this doll (click on it when console is open) would be much faster than replaying quests.
